sylius_twig_hooks:
    hooks:
        'sylius_admin.base#javascripts':
            monsieurbiz_markerio:
                template: '@MonsieurBizSyliusMarkerioPlugin/admin/metadata.html.twig'
                priority: -100
