services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    MonsieurBiz\SyliusMarkerioPlugin\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Event/'
            - '../src/MonsieurBizSyliusMarkerioPlugin.php'
