name: Security

permissions:
    contents: read

on:
    push:
    pull_request:

jobs:

    security:

        name: Security check (PHP 8.3)

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.3'
                  extensions: gd, intl, json
                  ini-values: date.timezone=UTC

            - name: Set project php-version
              run: |
                  echo 8.3 > .php-version

            - name: Determine composer cache directory
              id: composer-cache-directory
              run: echo "directory=$(composer config cache-dir)" >> $GITHUB_OUTPUT

            - name: Cache dependencies installed with composer
              uses: actions/cache@v4
              id: cache-composer
              with:
                  path: ${{ steps.composer-cache-directory.outputs.directory }}
                  key: composer2-php:8.3-${{ hashFiles('**/composer.json') }}
                  restore-keys: composer2-php:8.3-
            - name: Ensure that composer cache directory exists
              run: mkdir -p ${{ steps.composer-cache-directory.outputs.directory }}

            - name: Composer Github Auth
              run: composer config -g github-oauth.github.com ${{ github.token }}

            - name: Install PHP dependencies
              run: composer update --prefer-dist

            - name: Audit PHP dependencies
              run: composer audit
